[package]
name = "wpm"
version = "0.1.0"
edition = "2021"

[dependencies]
dirs = { workspace = true }
parking_lot = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

toml = "0.8"
