[Unit]
Name = "desktop"
Description = "everything I need to work on Windows"
Requires = ["komorebi"]

[Service]
Kind = "Oneshot"
Autostart = true
Executable = "msg.exe"
Arguments = [
    "*",
    "Desktop recipe completed!",
]
Restart = "Never"
