[Unit]
Name = "kanata"
Description = "software keyboard remapper"

[Service]
Kind = "Simple"
Executable = "kanata.exe"
Arguments = [
    "-c",
    "$USERPROFILE/minimal.kbd",
    "--port",
    "9999",
]
Restart = "Never"

[Service.Healthcheck]
LivenessSec = 1
