[Unit]
Name = "kanata"
Description = "software keyboard remapper"

[Service]
Kind = "Simple"
Restart = "Never"

[Service.ExecStart]
Executable = "kanata.exe"
Arguments = [
    "-c",
    "$USERPROFILE/minimal.kbd",
    "--port",
    "9999",
]

[Service.Healthcheck.Process]
DelaySec = 1
