[unit]
name = "komorebi"
description = "tiling window management for Windows"
requires = [
    "whkd",
    "kanata",
]

[service]
kind = "Simple"
autostart = false
executable = "komorebi.exe"
arguments = [
    "--config",
    "$USERPROFILE/.config/komorebi/komorebi.json",
]
environment = [[
    "KOMOREBI_CONFIG_HOME",
    "$USERPROFILE/.config/komorebi",
]]
shutdown = [
    "komorebic stop",
    "komorebic restore-windows"
]

[service.healthcheck]
Command = "komorebic state"
