[Unit]
Name = "komorebi"
Description = "tiling window management for Windows"
Requires = [
    "whkd",
    "kanata",
]

[Service]
Kind = "Simple"
Restart = "Never"

[Service.ExecStart]
Executable = "komorebi.exe"
Arguments = [
    "--config",
    "$USERPROFILE/.config/komorebi/komorebi.json",
]
Environment = [[
    "KOMOREBI_CONFIG_HOME",
    "$USERPROFILE/.config/komorebi",
]]

[Service.Healthcheck.Command]
Executable = "komorebic.exe"
Arguments = ["state"]

[[Service.Shutdown]]
Executable = "komorebic.exe"
Arguments = ["stop"]

[[Service.Shutdown]]
Executable = "komorebic.exe"
Arguments = ["restore-windows"]
