[Unit]
Name = "komorebi"
Description = "tiling window management for Windows"
Requires = [
    "whkd",
    "kanata",
]

[Service]
Kind = "Simple"
Executable = "komorebi.exe"
Arguments = [
    "--config",
    "$USERPROFILE/.config/komorebi/komorebi.json",
]
Environment = [[
    "KOMOREBI_CONFIG_HOME",
    "$USERPROFILE/.config/komorebi",
]]
Restart = "Never"
Shutdown = [
    "komorebic.exe stop",
    "komorebic.exe restore-windows",
]

[Service.Healthcheck]
Command = "komorebic.exe state"
