[Unit]
Name = "masir"
Description = "focus follows mouse for Windows"
Requires = ["komorebi"]

[Service]
Kind = "Simple"
Restart = "Never"

[Service.ExecStart]
Executable = "masir.exe"

[Service.Healthcheck]
LivenessSec = 1
