[Unit]
Name = "masir"
Description = "focus follows mouse for Windows"
Requires = ["komorebi"]

[Service]
Kind = "Simple"
Executable = "masir.exe"
Restart = "Never"

[Service.Healthcheck]
LivenessSec = 1
