[unit]
name = "masir"
description = "focus follows mouse for Windows"
requires = ["komorebi"]

[service]
kind = "Simple"
autostart = false
executable = "masir.exe"

[service.healthcheck]
LivenessSeconds = 1
