[Unit]
Name = "desktop"
Description = "Everything I need to work on Windows"
Requires = [
    "komorebi",
    "komorebi-bar",
    "mousemaster",
]

[Service]
Kind = "Oneshot"
Restart = "Never"

[Service.ExecStart]
Executable = "msg.exe"
Arguments = [
    "*",
    "Desktop recipe completed!",
]
