[Unit]
Name = "komorebi-bar"
Description = "Status bar for komorebi"
Requires = ["komorebi"]

[Resources]
CONFIGURATION_FILE = "https://raw.githubusercontent.com/LGUG2Z/komorebi/refs/tags/v0.1.35/docs/komorebi.bar.example.json"

[Service]
Kind = "Simple"
Environment = [[
    "KOMOREBI_CONFIG_HOME",
    "$USERPROFILE/.config/komorebi",
]]
Restart = "Never"

[Service.ExecStart]
Arguments = [
    "--config",
    "{{ Resources.CONFIGURATION_FILE }}",
]

[Service.ExecStart.Executable]
Package = "komorebi"
Version = "0.1.35"
Manifest = "https://raw.githubusercontent.com/ScoopInstaller/Extras/8e21dc2cd902b865d153e64a078d97d3cd0593f7/bucket/komorebi.json"
Target = "komorebi-bar.exe"

[Service.Healthcheck.Process]
DelaySec = 1
