[Unit]
Name = "komorebi"
Description = "Tiling window management for Windows"
Requires = [
    "whkd",
    "kanata",
]

[Resources]
CONFIGURATION_FILE = "https://raw.githubusercontent.com/LGUG2Z/komorebi/refs/tags/v0.1.35/docs/komorebi.example.json"

[Service]
Kind = "Simple"
Restart = "Never"

[[Service.ExecStartPre]]
Executable = "komorebic.exe"
Arguments = ["fetch-asc"]

[Service.ExecStart]
Arguments = [
    "--config",
    "{{ Resources.CONFIGURATION_FILE }}",
]
Environment = [[
    "KOMOREBI_CONFIG_HOME",
    "$USERPROFILE/.config/komorebi",
]]

[Service.ExecStart.Executable]
Package = "komorebi"
Version = "0.1.35"
Manifest = "https://raw.githubusercontent.com/ScoopInstaller/Extras/8e21dc2cd902b865d153e64a078d97d3cd0593f7/bucket/komorebi.json"
Target = "komorebi.exe"

[[Service.ExecStop]]
Executable = "komorebic.exe"
Arguments = ["stop"]

[[Service.ExecStopPost]]
Executable = "komorebic.exe"
Arguments = ["restore-windows"]

[Service.Healthcheck.Command]
Executable = "komorebic.exe"
Arguments = ["state"]
DelaySec = 1
