[Unit]
Name = "komokana"
Description = "Automatic application-aware keyboard layer switching for Windows"
Requires = [
    "komorebi",
    "kanata",
]

[Service]
Kind = "Simple"
Autostart = true
Restart = "OnFailure"
RestartSec = 2

[Service.ExecStart]
Executable = "komokana.exe"
Arguments = [
    "--kanata-port",
    "9999",
    "--configuration",
    "$USERPROFILE/komokana.yaml",
    "--default-layer",
    "qwerty",
]

[Service.Healthcheck.Process]
DelaySec = 1
