[Unit]
Name = "komokana"
Description = "Automatic application-aware keyboard layer switching for Windows"
Requires = [
    "komorebi",
    "kanata",
]

[Resources]
CONFIGURATION_FILE = "https://raw.githubusercontent.com/LGUG2Z/komokana/refs/tags/v0.1.5/komokana.example.yaml"

[Service]
Kind = "Simple"
Restart = "OnFailure"
RestartSec = 2

[Service.ExecStart]
Arguments = [
    "--kanata-port",
    "9999",
    "--configuration",
    "{{ Resources.CONFIGURATION_FILE }}",
    "--default-layer",
    "qwerty",
]

[Service.ExecStart.Executable]
Package = "komokana"
Version = "0.1.5"
Manifest = "https://raw.githubusercontent.com/ScoopInstaller/Extras/e633292b4e1101273caac59ffcb4a7ce7ee7a2e8/bucket/komokana.json"

[Service.Healthcheck.Process]
DelaySec = 1
